name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  exif: ^3.3.0
  path: ^1.9.1
  camera: ^0.11.3
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.15.0
  flutter_tts: ^4.2.3
  share_plus: ^12.0.1
  google_mlkit_translation: ^0.13.0
  google_mlkit_language_id: ^0.13.0
  http: ^1.6.0
  translator: ^1.0.4+1
  flutter_colorpicker: ^1.1.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/